local-encfs:
  build: encfs/
  volumes:
  - /mnt/butterfinger:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  restart: always
  env_file:
  - /opt/butterfinger/config/local-encfs.env
  privileged: true

acd-mount:
  build: acd-cli/
  volumes:
  - /mnt/butterfinger:/mnt:shared
  - /opt/butterfinger/config/acd-cli:/config
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  restart: always
  env_file:
  - /opt/butterfinger/config/acd-mount.env
  privileged: true

acd-encfs:
  build: encfs/
  volumes:
  - /mnt/butterfinger:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  restart: always
  env_file:
  - /opt/butterfinger/config/acd-encfs.env
  privileged: true

unionfs:
  build: unionfs/
  volumes:
  - /mnt/butterfinger:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  restart: always
  env_file:
  - /opt/butterfinger/config/unionfs.env
  privileged: true

plexpass:
  image: wernight/plex-media-server:latest
  devices:
  - /dev/fuse
  ports:
    - 32400:32400
    - 1900:1900/udp
    - 32469:32469
    - 3005:3005
    - 5353:5353/udp
    - 8324:8324
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
  cap_add:
  - MKNOD
  - SYS_ADMIN
  net: host
  restart: always
  env_file:
  - /opt/butterfinger/config/plex-media-server.env
  volumes:
  - /opt/butterfinger/config/plex:/config
  - /mnt/butterfinger/union:/data:shared
  privileged: true
