local-encfs:
  build: encfs/
  volumes:
  - /opt/butterfinger/data:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  env_file:
  - /opt/butterfinger/config/local-encfs.env
  privileged: true

acd-mount:
  build: acd-cli/
  volumes:
  - /opt/butterfinger/data:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  env_file:
  - /opt/butterfinger/config/acd-mount.env
  privileged: true

acd-encfs:
  build: encfs/
  volumes:
  - /opt/butterfinger/data:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  env_file:
  - /opt/butterfinger/config/acd-encfs.env
  privileged: true

unionfs:
  build: unionfs/
  volumes:
  - /opt/butterfinger/data:/mnt:shared
  devices:
  - /dev/fuse
  cap_add:
  - MKNOD
  - SYS_ADMIN
  env_file:
  - /opt/butterfinger/config/unionfs.env
  privileged: true

plexpass:
  image: timhaak/plexpass
  devices:
  - /dev/fuse
  ports:
  - 80:32400
  cap_add:
  - MKNOD
  - SYS_ADMIN
  env_file:
  - /opt/butterfinger/config/plex-media-server.env
  volumes:
  - /opt/butterfinger/config:/config
  - /opt/butterfinger/data:/data
  privileged: true
