local-encfs:
  build: encfs/
  volumes:
   - /opt/butterfinger/data:/mnt:shared:shared
  environment:
    MOUNT_SOURCE: /mnt/local-encrypted
    MOUNT_TARGET: /mnt/local-decrypted
    ENCFS6_CONFIG: /mnt/local-encrypted/.encfs6.xml
    ENCFS_PASS: $ENCFS_PASS
  privileged: true

acd-mount:
  build: acd-cli/
  volumes:
   - /opt/butterfinger/data:/mnt:shared
  environment:
    ACD_CLI_CACHE_PATH: /mnt/acd_cli/
    MOUNT_TARGET: /mnt/acd-encrypted
  privileged: true

acd-encfs:
  build: encfs/
  volumes:
   - /opt/butterfinger/data:/mnt:shared
  environment:
    MOUNT_SOURCE: /mnt/acd-encrypted
    MOUNT_TARGET: /mnt/acd-decrypted
    WAIT_FOR_MNT: /mnt/acd-encrypted
    ENCFS6_CONFIG: /mnt/local-encrypted/.encfs6.xml
    ENCFS_PASS: $ENCFS_PASS
  privileged: true

unionfs:
  build: unionfs/
  volumes:
   - /opt/butterfinger/data:/mnt:shared
  environment:
    MOUNT_UNITE: /mnt/local-decrypted=RW:/mnt/acd-decrypted
    MOUNT_TARGET: /mnt/union/
    WAIT_FOR_MNT: /mnt/acd-decrypted
  privileged: true
